a=input("enter first number:")  
b=input("enter second number:")
print("addition:",int(a)+int(b))
print("subtraction:",int(a)-int(b))
print("multiplication:",int(a)*int(b))
print("division:",int(a)/int(b))
